import { useCallback, useEffect, useRef, useState } from 'react';

export interface JobSummary {
  id: string;
  title: string;
  modelId?: string;
  status: string;
  mode?: 'interactive' | 'loop' | 'graph';
  workspaceId?: string;
  workdir?: string;
  createdAt: number;
  updatedAt: number;
  pinnedAt?: number;
  sessionCount: number;
  scheduleId?: string;
  shareToken?: string;
}

interface ListJobsResponse {
  jobs: JobSummary[];
  nextCursor?: string;
  hasMore?: boolean;
  version?: number;
  dailyStats?: Record<string, DailyStatsEntry>;
}

// DailyStatsEntry mirrors the backend's per-day total bundled with the
// list response. Keyed by YYYY-MM-DD on the parent map; days with no
// data are absent (treat as "no statistics").
export interface DailyStatsEntry {
  totalMs: number;
  turnCount: number;
}

interface UseJobListOptions {
  // Filter workspace. When undefined → global cross-workspace list.
  workspaceId?: string;
  // When true, jobs auto-generated by a scheduled task (ScheduleID != "") are
  // dropped on the backend BEFORE pagination. Doing it server-side keeps each
  // page full — a workspace dominated by scheduled jobs would otherwise show
  // an empty first page if we filtered on the client.
  excludeScheduled?: boolean;
  // Page size requested from the backend. The backend caps at 200.
  pageSize?: number;
  // Poll interval for background refresh. Polling uses If-None-Match so most
  // requests short-circuit to 304 when the workspace hasn't mutated.
  pollIntervalMs?: number;
  // Tighter interval used when any job is running/pending (so the UI picks up
  // status transitions quickly). Set to 0 to disable.
  activePollIntervalMs?: number;
  // Re-fetch when the window regains focus.
  refetchOnFocus?: boolean;
  // When true, all fetching is completely disabled. Useful for share/readonly
  // pages where the job list is not needed.
  disabled?: boolean;
}

interface UseJobListReturn {
  jobs: JobSummary[];
  hasMore: boolean;
  isLoading: boolean;
  isLoadingMore: boolean;
  loadMore: () => Promise<void>;
  refresh: () => Promise<void>;
  // Remove a job from local state (optimistic for delete flows — callers
  // should invoke this after a successful DELETE so the item disappears
  // immediately without waiting for the next poll).
  removeJob: (jobId: string) => void;
  // Merge a partial update into an existing job (e.g. title refreshed).
  patchJob: (jobId: string, patch: Partial<JobSummary>) => void;
  // Per-day usage totals keyed by YYYY-MM-DD. Updated on every successful
  // (non-304) list fetch. Days with no data are absent from the map. The
  // ChatPage / Sidebar render this next to the day group header.
  dailyStats: Record<string, DailyStatsEntry>;
}

const DEFAULT_PAGE_SIZE = 50;
const DEFAULT_POLL_INTERVAL_MS = 60_000;
const DEFAULT_ACTIVE_POLL_INTERVAL_MS = 5_000;

function compareJobs(a: JobSummary, b: JobSummary): number {
  const aPinned = (a.pinnedAt ?? 0) > 0;
  const bPinned = (b.pinnedAt ?? 0) > 0;
  if (aPinned !== bPinned) return aPinned ? -1 : 1;
  if ((a.pinnedAt ?? 0) !== (b.pinnedAt ?? 0)) return (b.pinnedAt ?? 0) - (a.pinnedAt ?? 0);
  if (a.updatedAt !== b.updatedAt) return b.updatedAt - a.updatedAt;
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

function dayKeyFromTimestamp(ts?: number): string | null {
  if (!ts || ts <= 0) return null;
  const d = new Date(ts);
  if (Number.isNaN(d.getTime())) return null;
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

/**
 * Shared hook for loading a paginated, ETag-cached job list.
 *
 * Previously the three pages that showed a job list (ChatPage / JobChat
 * dropdown / Sidebar) each fetched the full unpaginated list every 60s and
 * received the entire LoopConfig + Progress.Results tree for every job. For
 * workspaces with thousands of jobs that produced multi-megabyte responses
 * and rendered hundreds of unused DOM nodes.
 *
 * This hook centralizes the fetch behavior with:
 *   - Cursor-based pagination (load-more / infinite scroll).
 *   - Conditional GETs via If-None-Match so idle polls short-circuit to 304.
 *   - Tight polling while a job is running, slow polling otherwise.
 */
export function useJobList(options: UseJobListOptions = {}): UseJobListReturn {
  const {
    workspaceId,
    excludeScheduled = false,
    pageSize = DEFAULT_PAGE_SIZE,
    pollIntervalMs = DEFAULT_POLL_INTERVAL_MS,
    activePollIntervalMs = DEFAULT_ACTIVE_POLL_INTERVAL_MS,
    refetchOnFocus = true,
    disabled = false,
  } = options;

  const [jobs, setJobs] = useState<JobSummary[]>([]);
  const [hasMore, setHasMore] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const [dailyStats, setDailyStats] = useState<Record<string, DailyStatsEntry>>({});

  // Refs so async callers always see the latest values without retriggering.
  const jobsRef = useRef<JobSummary[]>([]);
  jobsRef.current = jobs;
  const nextCursorRef = useRef<string>('');
  const hasMoreRef = useRef(false);
  hasMoreRef.current = hasMore;
  // ETag of the first page only. Background polls always fetch the first page
  // (to pick up newly-created jobs at the top), and we only short-circuit when
  // that ETag hasn't changed.
  const firstPageEtagRef = useRef<string>('');
  // Guard against overlapping requests — a slow network plus an aggressive
  // poll could otherwise double-fetch.
  const inFlightRef = useRef(false);

  // Prevent stale responses (e.g. after switching workspace/filter) from
  // overwriting newer state.
  const requestSeqRef = useRef(0);
  const abortRef = useRef<AbortController | null>(null);

  const buildUrl = useCallback(
    (cursor: string) => {
      const params = new URLSearchParams();
      if (workspaceId) params.set('workspaceId', workspaceId);
      if (cursor) params.set('cursor', cursor);
      params.set('limit', String(pageSize));
      if (excludeScheduled) params.set('excludeScheduled', 'true');
      return `/api/v1/job/list?${params.toString()}`;
    },
    [workspaceId, pageSize, excludeScheduled]
  );

  // Fetch a single page. `mode` controls how the result is merged:
  //   - "replace": initial load / manual refresh — replace the full list.
  //   - "poll":    background refresh — merge by id so load-more state is
  //                preserved (new jobs prepend, existing jobs update in place).
  //   - "append":  load-more — append to the existing list.
  const fetchPage = useCallback(
    async (cursor: string, mode: 'replace' | 'poll' | 'append'): Promise<void> => {
      if (inFlightRef.current && mode === 'poll') return;
      const seq = ++requestSeqRef.current;

      // Replacing the list (refresh / workspace switch) should cancel any
      // in-flight request so old responses don't race the new state.
      if (mode === 'replace') {
        try { abortRef.current?.abort(); } catch { /* ignore */ }
      }
      const controller = new AbortController();
      abortRef.current = controller;

      inFlightRef.current = true;
      try {
        const headers: Record<string, string> = {};
        if (mode === 'poll' && !cursor && firstPageEtagRef.current) {
          headers['If-None-Match'] = firstPageEtagRef.current;
        }
        const response = await fetch(buildUrl(cursor), { headers, signal: controller.signal });
        if (response.status === 304) {
          // Nothing changed — keep state as-is.
          return;
        }
        if (!response.ok) return;

        // Capture the ETag so the next poll can send If-None-Match. We only
        // track the first-page ETag; pagination pages each have their own
        // ETag but we never poll those directly.
        if (!cursor) {
          firstPageEtagRef.current = response.headers.get('ETag') || '';
        }

        const data = (await response.json()) as ListJobsResponse;
        // Ignore stale results.
        if (seq !== requestSeqRef.current) return;
        const fetched = data.jobs || [];
        const fetchedDayKeys = Array.from(new Set(
          fetched
            .map((j) => dayKeyFromTimestamp(j.updatedAt))
            .filter((key): key is string => !!key)
        ));

        // Replace stats for the days touched by this page. Omitted dailyStats means
        // "no stats for those days" rather than "keep whatever the previous poll had".
        setDailyStats((prev) => {
          const next = { ...prev };
          for (const key of fetchedDayKeys) delete next[key];
          return data.dailyStats ? { ...next, ...data.dailyStats } : next;
        });

        if (mode === 'replace') {
          setJobs(fetched);
          nextCursorRef.current = data.nextCursor || '';
          setHasMore(!!data.hasMore);
          return;
        }

        if (mode === 'append') {
          setJobs((prev) => {
            const seen = new Set(prev.map((j) => j.id));
            const merged = [...prev];
            for (const j of fetched) {
              if (!seen.has(j.id)) merged.push(j);
            }
            return merged;
          });
          nextCursorRef.current = data.nextCursor || '';
          setHasMore(!!data.hasMore);
          return;
        }

        // mode === 'poll': merge the freshly-fetched first page into whatever
        // we already have without clobbering pages the user scrolled to via
        // load-more. New jobs (not in our local list) get prepended; existing
        // jobs get updated in place. Items that lived past the fetched first
        // page stay put, but items that *would* have appeared on the first
        // page if they still existed are treated as deleted server-side and
        // dropped — otherwise jobs deleted from another tab/process would
        // linger until the user hit refresh.
        setJobs((prev) => {
          const fetchedIds = new Set(fetched.map((j) => j.id));
          const prevById = new Map(prev.map((j) => [j.id, j] as const));
          const merged: JobSummary[] = [];
          for (const j of fetched) {
            merged.push({ ...(prevById.get(j.id) ?? {}), ...j });
          }
          // Backend returns the first page in canonical list order, so the
          // last fetched entry defines the page's lower bound. A prev item
          // that sorts strictly before that bound should have appeared on this
          // page if the server still had it — if it didn't, it's gone. Ties at
          // the boundary are ambiguous (could be rank-51 with identical sort
          // keys) so we keep those to avoid a false drop.
          const hasMoreFlag = !!data.hasMore;
          const cutoff = fetched.length > 0 ? fetched[fetched.length - 1] : null;
          for (const j of prev) {
            if (fetchedIds.has(j.id)) continue;
            // When there are no more pages, the fetched set IS the complete
            // list — anything missing was deleted.
            if (!hasMoreFlag) continue;
            // Empty first page but hasMore claims otherwise: pathological,
            // keep prev untouched.
            if (cutoff === null) {
              merged.push(j);
              continue;
            }
            // Strictly before the page cutoff → must have been deleted.
            if (compareJobs(j, cutoff) < 0) continue;
            merged.push(j);
          }
          // Sort once to maintain backend order (pinned first, then UpdatedAt-desc).
          merged.sort(compareJobs);
          return merged;
        });
      } catch (err) {
        if (err instanceof Error && err.name === 'AbortError') return;
        console.error('[useJobList] fetch failed:', err);
      } finally {
        // Only the latest request should clear the in-flight flag; otherwise a
        // replaced/aborted earlier request could clobber a newer request.
        if (abortRef.current === controller) {
          inFlightRef.current = false;
          abortRef.current = null;
        }
      }
    },
    [buildUrl]
  );

  // Abort in-flight fetch on unmount.
  useEffect(() => {
    return () => {
      try { abortRef.current?.abort(); } catch { /* ignore */ }
    };
  }, []);

  const refresh = useCallback(async () => {
    setIsLoading(true);
    firstPageEtagRef.current = '';
    nextCursorRef.current = '';
    // A manual refresh is the only place where we want to drop accumulated
    // dailyStats — workspace switch / explicit refresh both go through
    // here, and stale stats from a previous workspace would otherwise
    // leak into the new view until each day is re-fetched.
    setDailyStats({});
    try {
      await fetchPage('', 'replace');
    } finally {
      setIsLoading(false);
    }
  }, [fetchPage]);

  const loadMore = useCallback(async () => {
    if (!hasMoreRef.current || !nextCursorRef.current) return;
    setIsLoadingMore(true);
    try {
      await fetchPage(nextCursorRef.current, 'append');
    } finally {
      setIsLoadingMore(false);
    }
  }, [fetchPage]);

  const removeJob = useCallback((jobId: string) => {
    setJobs((prev) => prev.filter((j) => j.id !== jobId));
  }, []);

  const patchJob = useCallback((jobId: string, patch: Partial<JobSummary>) => {
    setJobs((prev) => prev.map((j) => (j.id === jobId ? { ...j, ...patch } : j)).sort(compareJobs));
  }, []);

  // Initial load + workspace changes reset the list.
  useEffect(() => {
    if (disabled) return;
    void refresh();
  }, [refresh, disabled]);

  // Polling + focus refetch. Poll interval adapts to whether anything is
  // running.
  useEffect(() => {
    if (disabled) return;

    const onFocus = () => {
      if (refetchOnFocus) void fetchPage('', 'poll');
    };
    if (refetchOnFocus) window.addEventListener('focus', onFocus);

    // Polling disabled: skip the interval machinery entirely. Without this
    // short-circuit the `check` timer below would wake every second to
    // re-evaluate an interval that never becomes > 0.
    if (pollIntervalMs <= 0) {
      return () => {
        if (refetchOnFocus) window.removeEventListener('focus', onFocus);
      };
    }

    const tick = () => {
      void fetchPage('', 'poll');
    };
    const pickInterval = () => {
      const hasActive = jobsRef.current.some(
        (j) => j.status === 'running' || j.status === 'pending'
      );
      return hasActive && activePollIntervalMs > 0 ? activePollIntervalMs : pollIntervalMs;
    };

    let interval = pickInterval();
    let handle: ReturnType<typeof setInterval> | null = setInterval(tick, interval);

    // Re-evaluate the interval whenever `jobs` changes — if a job transitions
    // into running we want to switch to the faster poll rate.
    const check = setInterval(() => {
      const next = pickInterval();
      if (next !== interval) {
        interval = next;
        if (handle) clearInterval(handle);
        handle = setInterval(tick, interval);
      }
    }, 1000);

    return () => {
      if (handle) clearInterval(handle);
      clearInterval(check);
      if (refetchOnFocus) window.removeEventListener('focus', onFocus);
    };
  }, [fetchPage, pollIntervalMs, activePollIntervalMs, refetchOnFocus, disabled]);

  return {
    jobs,
    hasMore,
    isLoading,
    isLoadingMore,
    loadMore,
    refresh,
    removeJob,
    patchJob,
    dailyStats,
  };
}
