package job

import (
	"context"

	"github.com/cloudwego/eino/schema"
	"github.com/fanlv/quartet/repository"
	"github.com/fanlv/quartet/services/script"
	"github.com/fanlv/quartet/services/usagestats"
	"github.com/fanlv/quartet/services/workspace"
	"github.com/fanlv/quartet/types/model"
)

type Service interface {
	// CRUD
	Create(job *model.Job) error
	Get(jobID string) (*model.Job, bool)
	// GetWithSnapshotSeq returns the job state together with the SSE
	// resume sequence the snapshot endpoint should hand the client. It
	// reads the buffer's seq BEFORE the job state on purpose: with the
	// §1.4 contract that B-class state writes precede event publish,
	// reading seq first guarantees the returned job state reflects every
	// event up to (and possibly past) the returned seq, so a client
	// subscribing from seq+1 will never miss an event whose state
	// updates the snapshot already shows.
	GetWithSnapshotSeq(jobID string) (*model.Job, uint64, bool)
	List() []*model.Job
	ListByWorkspace(wsID string) []*model.Job
	// ListByWorkspacePaged returns a slice of JobSummary for a workspace (or all
	// workspaces when wsID is empty), ordered by pinned jobs first, then
	// UpdatedAt DESC with ID as tiebreaker. Cursor is an opaque string returned by a previous call's
	// NextCursor (empty for first page). The version returned is the monotonic
	// workspace-scoped counter used to build ETags — callers should pass it
	// through to the HTTP layer for conditional GET support.
	//
	// When excludeScheduled is true, Jobs with a non-empty ScheduleID (i.e.
	// those auto-generated by a scheduled task trigger) are filtered out
	// BEFORE pagination, so hiding them cannot leave the first page empty
	// when the workspace is dominated by scheduled-task Jobs.
	ListByWorkspacePaged(wsID, cursor string, limit int, excludeScheduled bool) (summaries []model.JobSummary, nextCursor string, hasMore bool, version int64)
	// WorkspaceListVersion returns the monotonic version for a workspace (or
	// the global version when wsID is empty). Increments on any job mutation
	// that would affect the listing. Used for ETag / If-None-Match handling.
	WorkspaceListVersion(wsID string) int64
	Delete(jobID string)
	// MarkDeleted sets job.Deleted=true atomically (Get + mutate + persist
	// under the service's internal lock) so concurrent Save calls can't
	// overwrite the flag with a stale snapshot.
	MarkDeleted(jobID string) error
	// UpdateTitle updates only the title of a job, avoiding stale-copy overwrites.
	UpdateTitle(jobID string, title string) error
	// UpdatePinned updates only the pinned state of a job. Pinned jobs float to
	// the top of list endpoints, ordered by the time they were pinned.
	UpdatePinned(jobID string, pinned bool) (pinnedAt int64, err error)
	// EnsureShareToken returns the job's existing share token, or atomically
	// generates one and persists it if none exists. Both the read of the
	// current token and the write of a new one happen under the service's
	// internal lock so concurrent callers can't each mint a separate token.
	EnsureShareToken(jobID string, generate func() (string, error)) (string, error)
	// ClearShareToken wipes the job's share token atomically.
	ClearShareToken(jobID string) error
	// SetFirstModelID denormalizes the first session's ModelID onto the Job so
	// that the list endpoint does not have to open each session's metadata file
	// (the old implementation was N+1 in I/O). It is an idempotent setter: if
	// the job already has the same value it is a no-op.
	SetFirstModelID(jobID string, modelID string) error

	// ReplaceLoopConfig swaps a non-running loop job's whole LoopConfig (full
	// structure edit). It recomputes the progress denominator and reconciles
	// Resume / CurrentPath / Results against the new flow so a subsequent
	// Continue resumes from a valid position. Returns ErrJobRunning if the job
	// is currently running (use UpdateRunningStepFields for that case). The
	// returned JobProgress lets the caller refresh the client immediately.
	ReplaceLoopConfig(ctx context.Context, jobID string, cfg *model.LoopConfig) (*model.JobProgress, error)
	// UpdateRunningStepFields applies the per-step editable fields (message,
	// agentType, modelId, acpMode) from newFlow onto a RUNNING job's live flow,
	// in place. It first verifies the structure is identical (same node tree by
	// id/type/round settings/children order) and returns ErrLoopStructureChanged
	// when it differs — running jobs may only edit fields, not structure. The
	// change takes effect for steps that have not started yet (and, for
	// model/agent/mode, only steps that create a fresh session).
	UpdateRunningStepFields(ctx context.Context, jobID string, newFlow []model.FlowNode) error

	// Start launches the job's LoopConfig execution. Resets progress.
	Start(ctx context.Context, jobID string, runner JobRunner) error
	// Continue resumes a stopped loop job from its saved cursor.
	Continue(ctx context.Context, jobID string, runner JobRunner) error
	// SendMessage sends a message to an existing job session. Appends to progress.
	SendMessage(ctx context.Context, jobID string, runner JobRunner, opts *SendMessageOptions) error
	Stop(jobID string)
	// RequestGracefulStop asks a running loop job to stop at the next step
	// boundary: the in-flight step runs to completion and resume is preserved,
	// so Continue resumes cleanly from the next step. Unlike Stop it does not
	// cancel the context or interrupt the current step. No-op if the job is not
	// running; the request is cleared when the run relaunches.
	RequestGracefulStop(jobID string)
	// CancelGracefulStop drops a pending graceful-stop request so the loop keeps
	// running. No-op if no request is pending. Only meaningful before the request
	// is consumed at the next step boundary; once consumed the loop has already
	// stopped and the user must Continue instead.
	CancelGracefulStop(jobID string)
	// IsGracefulStopSupported reports whether the current active run can consume
	// a graceful-stop request. Loop runs can; interactive SendMessage runs cannot.
	IsGracefulStopSupported(jobID string) bool
	// StopAndWait cancels a running job and blocks until its runLoop goroutine exits.
	StopAndWait(jobID string)
	// StopAll cancels all running jobs and waits for their goroutines to exit.
	// Used during graceful shutdown.
	StopAll()

	// SSE pub/sub
	//
	// Subscribe creates a reader resuming from startSeq+1. startSeq=0 means
	// "start at the buffer's current tail" (used by IM gateway and any
	// caller that doesn't carry a Last-Event-ID). Returns ErrSeqGone when
	// startSeq is older than the buffer's GC head — the SSE handler maps
	// this to HTTP 410 so the client falls back to "re-fetch snapshot".
	Subscribe(jobID string, startSeq uint64) (*bufferReader, error)
	// SnapshotSeq returns the resume sequence the snapshot endpoint should
	// hand out as the new subscriber's initial Last-Event-ID. If a round
	// is in flight, returns round_start - 1 so the subscriber sees the
	// round boundary; otherwise returns the current tail.
	SnapshotSeq(jobID string) uint64
	Publish(jobID string, event any)
	// PublishTransient broadcasts an event WITHOUT adding it to the per-job
	// buffer. Use for transient UI feedback (e.g. slash-command results)
	// that must not reappear on page refresh / SSE reconnect.
	PublishTransient(jobID string, event any)

	// BufferStats returns a snapshot of the per-job event buffer state for
	// observability (current event count, live reader count, head/next seq,
	// max cursor lag, GC counters). Returns the zero value when no buffer
	// exists for jobID yet (e.g. job has not published anything).
	BufferStats(jobID string) BufferStats

	// SetOnJobDone registers a callback invoked when a loop job finishes (completed/failed/stopped).
	SetOnJobDone(fn func(job *model.Job))

	// SetUsageRecorder wires the optional usage-stats sink. Every step
	// finalize position will submit a Snapshot once a recorder is set.
	// Passing nil disables recording (e.g. for tests).
	SetUsageRecorder(r usagestats.Recorder)
}

// SendMessageOptions provides parameters for sending a message to an existing session.
type SendMessageOptions struct {
	SessionID       string
	ClientMessageID string
	Messages        []*schema.Message

	// Agent/model configuration for this message run.
	AgentType string
	ModelID   string
	ACPMode   string
}

// getMessages returns the Messages if opts is non-nil, otherwise nil.
func (o *SendMessageOptions) getMessages() []*schema.Message {
	if o == nil {
		return nil
	}
	return o.Messages
}

func NewService(wsSvc workspace.Service, scriptSvc script.Service) (Service, error) {
	s := &serviceImpl{
		jobs:                   make(map[string]*model.Job),
		repos:                  make(map[string]repository.JobRepo),
		wsSvc:                  wsSvc,
		scriptSvc:              scriptSvc,
		bus:                    newBusOwner(),
		cancels:                make(map[string]*cancelEntry),
		dones:                  make(map[string]chan struct{}),
		interactivePriorStatus: make(map[string]model.JobStatus),
		wsListVersion:          make(map[string]int64),
		notifiedJobs:           make(map[string]struct{}),
		gracefulStops:          make(map[string]struct{}),
		loopRuns:               make(map[string]struct{}),
	}

	s.load()

	// Clean up temp files from previous runs that may have been interrupted.
	cleanupResidualTempFiles(workspaceWorkdirs(wsSvc))

	return s, nil
}

// workspaceWorkdirs returns the workdirs of all non-deleted workspaces so
// startup cleanup can scan for orphaned shell/control files left behind by
// SIGKILLed or OOM-killed steps.
func workspaceWorkdirs(wsSvc workspace.Service) []string {
	if wsSvc == nil {
		return nil
	}
	all := wsSvc.List()
	if len(all) == 0 {
		return nil
	}
	dirs := make([]string, 0, len(all))
	for _, ws := range all {
		if ws == nil || ws.Workdir == "" {
			continue
		}
		dirs = append(dirs, ws.Workdir)
	}
	return dirs
}
