import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuthPrincipal } from '../../auth';

interface Permission { id: string; description: string }
interface Role { id: string; name: string; description: string; permissions: string[]; builtIn: boolean; version: number }
interface UserRoleRef { roleIds: string[] | null }
async function apiError(response: Response) { const raw = await response.text(); try { const body = JSON.parse(raw) as { msg?: string; error?: string }; return body.msg || body.error || raw; } catch { return raw; } }

export function RoleManagement() {
  const principal = useAuthPrincipal();
  const canManage = principal?.permissions.includes('roles.manage') ?? false;
  const canReadUsers = principal?.permissions.includes('users.read') ?? false;
  const [roles, setRoles] = useState<Role[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]); const [selectedID, setSelectedID] = useState('');
  const [users, setUsers] = useState<UserRoleRef[]>([]);
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [selectedPermissions, setSelectedPermissions] = useState<string[]>([]); const [message, setMessage] = useState('');
  const selected = useMemo(() => roles.find((role) => role.id === selectedID), [roles, selectedID]);
  const load = useCallback(async () => { try { const [rr, pr, ur] = await Promise.all([fetch('/api/v1/roles'), fetch('/api/v1/permissions'), canReadUsers ? fetch('/api/v1/users') : null]); if (!rr.ok) throw new Error(await apiError(rr)); if (!pr.ok) throw new Error(await apiError(pr)); setRoles(((await rr.json()) as { roles: Role[] }).roles); setPermissions(((await pr.json()) as { permissions: Permission[] }).permissions); if (ur) { if (!ur.ok) throw new Error(await apiError(ur)); setUsers(((await ur.json()) as { users: UserRoleRef[] }).users); } } catch (error) { setMessage(String(error)); } }, [canReadUsers]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (selected) { setName(selected.name); setDescription(selected.description || ''); setSelectedPermissions(selected.permissions); } }, [selected]);
  const save = async () => { const endpoint = selected ? `/api/v1/roles/${selected.id}` : '/api/v1/roles'; const response = await fetch(endpoint, { method: selected ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...(selected ? { version: selected.version } : {}), name, description, permissions: selectedPermissions }) }); if (!response.ok) { setMessage(await apiError(response)); return; } setSelectedID(''); setName(''); setDescription(''); setSelectedPermissions([]); await load(); };
  const affectedUsers = selected ? users.filter((user) => (user.roleIds || []).includes(selected.id)).length : 0;
  const copy = () => { if (!selected) return; setSelectedID(''); setName(`${selected.name} 副本`); setDescription(selected.description); setSelectedPermissions([...selected.permissions]); };
  const remove = async () => { if (!selected || !window.confirm(`删除角色 ${selected.name}？当前有 ${affectedUsers} 个用户使用此角色。`)) return; const response = await fetch(`/api/v1/roles/${selected.id}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: selected.version }) }); if (!response.ok) { setMessage(await apiError(response)); return; } setSelectedID(''); await load(); };
  return <div className="auth-admin"><section className="settings-section"><h3 className="settings-section-title">角色与权限</h3>{message && <pre className="auth-admin-message">{message}</pre>}<div className="auth-admin-list">{roles.map((role) => { const count = users.filter((user) => (user.roleIds || []).includes(role.id)).length; return <button key={role.id} data-role-id={role.id} className={selectedID === role.id ? 'active' : ''} onClick={() => setSelectedID(role.id)}><strong>{role.name}</strong><span>{role.builtIn ? '内置角色' : '自定义角色'} · {role.permissions.length} 项权限{canReadUsers ? ` · ${count} 个用户` : ''}</span></button>; })}</div>{canManage && <button className="settings-btn settings-btn-secondary" data-testid="role-new-button" onClick={() => { setSelectedID(''); setName(''); setDescription(''); setSelectedPermissions([]); }}>新建角色</button>}</section><section className="settings-section"><h3 className="settings-section-title">{selected ? `编辑 ${selected.name}` : '创建角色'}</h3><div className="settings-form-group"><label className="settings-label">名称</label><input className="settings-input" data-testid="role-name-input" value={name} disabled={!canManage || selected?.builtIn} onChange={(event) => setName(event.target.value)} /></div><div className="settings-form-group"><label className="settings-label">说明</label><input className="settings-input" data-testid="role-description-input" value={description} disabled={!canManage || selected?.builtIn} onChange={(event) => setDescription(event.target.value)} /></div><div className="auth-admin-permissions">{permissions.map((permission) => <label key={permission.id}><input type="checkbox" data-permission-id={permission.id} disabled={!canManage || selected?.builtIn} checked={selectedPermissions.includes(permission.id)} onChange={(event) => setSelectedPermissions((current) => event.target.checked ? [...current, permission.id] : current.filter((id) => id !== permission.id))} /><span><strong>{permission.id}</strong><small>{permission.description}</small></span></label>)}</div>{canManage && <div className="settings-btn-group">{selected && <button className="settings-btn settings-btn-secondary" onClick={copy}>复制为新角色</button>}{!selected?.builtIn && <button className="settings-btn settings-btn-primary" data-testid="role-save-button" disabled={!name} onClick={() => void save()}>保存</button>}{selected && !selected.builtIn && <button className="settings-btn settings-btn-danger" onClick={() => void remove()}>删除</button>}</div>}</section></div>;
}
